### ISSUE TITLE
 EPERM: operation not permitted, uv_cwd

### ISSUE THREAD

**Issue by warreng** [soundcloud/intervene#5]
Hi, if I run the following command 
`intervene start local.trustedhousesitters.com.ts`

I see the below error message (I've replaced the name and secret)

```
2020-10-23T09:18:38.746Z [ERROR] Error starting admin server Error: Command failed: /Users/$name/.nvm/versions/node/v14.5.0/bin/node "/Users/$name/.nvm/versions/node/v14.5.0/lib/node_modules/intervene/dist/src/cli.js" admin 50300 --secret ${secret}
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at Yargs (/Users/$name/.nvm/versions/node/v14.5.0/lib/node_modules/intervene/node_modules/yargs/yargs.js:38:27)
    at Argv (/Users/$name/.nvm/versions/node/v14.5.0/lib/node_modules/intervene/node_modules/yargs/index.js:12:16)
    at Object.<anonymous> (/Users/$name/.nvm/versions/node/v14.5.0/lib/node_modules/intervene/node_modules/yargs/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/$name/.nvm/versions/node/v14.5.0/lib/node_modules/intervene/dist/src/cli.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}
```

**Comment by bruderstein** [comment]
This looks like an issue on newer MacOS, where access to certain directories is limited. Is your `local.trustedhousesitters.com.ts` under `/Users/$name/Documents/` for example? If so, try moving it out of there into something under your home directory. I believe you can also grant an exception, but not sure on the details there.

**Comment by warreng** [comment]
Yes, indeed moving it to my home directory worked. Thank you!
